package com.nguyen.polyglot.util

import com.nguyen.polyglot.R
import com.nguyen.polyglot.model.Language

object Constants {
    val supportedLanguages = listOf(
        Language("en_US", "English"),
        Language("es", "Spanish"),
        Language("fr", "French"),
        Language("de", "German"),
    )

    val allLanguages = listOf(Language("vi", "Vietnamese"), Language("en", "English"))

    const val apiURL = "http://192.168.0.235:4000"

    val dailyWordTopics = listOf("Random", "Common", "Food", "Traffic", "Weather", "Sport", "Science", "Nature", "Music", "Movie", "Money", "Emotion", "Clothing")
    val allFeedTopics = listOf("sports", "gaming", "business", "tech", "beauty", "movie", "politics")
    val productIds = listOf("polyglot_premium")

    val humanIcons = listOf(
        "human1",
        "human2",
        "human3",
        "human4",
        "human5",
        "human6",
        "human7",
        "human8",
        "human9",
        "human10",
        "human11",
        "human12",
        "human13",
        "human14",
        "human15",
        "human16",
        "human17",
        "human18",
        "human19",
        "human20",
        "human21",
        "human22",
        "human23",
        "human24",
        "human25",
        "human26",
        "human27",
        "human28",
        "human29",
        "human30",
        "human31",
        "human32",
        "human33",
        "human34",
        "human35",
        "human36",
        "human37",
        "human38",
        "human39",
        "human40",
        "human41",
        "human42",
        "human43",
        "human44",
        "human45",
        "human46",
        "human47",
        "human48",
        "human49",
        "human50",
    )


    val animalIcons = listOf(
        "animal1",
        "animal2",
        "animal3",
        "animal4",
        "animal5",
        "animal6",
        "animal7",
        "animal8",
        "animal9",
        "animal10",
        "animal11",
        "animal12",
        "animal13",
        "animal14",
        "animal15",
        "animal16",
        "animal17",
        "animal18",
        "animal19",
        "animal20",
        "animal21",
        "animal22",
        "animal23",
        "animal24",
        "animal25",
        "animal26",
        "animal27",
        "animal28",
        "animal29",
        "animal30",
        "animal31",
        "animal32",
        "animal33",
        "animal34",
        "animal35",
        "animal36",
        "animal37",
        "animal38",
        "animal39",
        "animal40",
        "animal41",
        "animal42",
        "animal43",
        "animal44",
        "animal45",
        "animal46",
        "animal47",
        "animal48",
        "animal49",
        "animal50",
    )
}