package com.nguyen.polyglot.util

import com.nguyen.polyglot.R
import com.nguyen.polyglot.model.Language

object Constants {
    val supportedLanguages = listOf(
        Language("en_US", "English"),
        Language("es", "Spanish"),
        Language("fr", "French"),
        Language("de", "German"),
    )

    val allLanguages = listOf("vie", "eng")

    const val apiURL = "http://192.168.0.239:4000"

    //    val humanIcons = listOf(
//        R.drawable.human1,
//        R.drawable.human2,
//        R.drawable.human3,
//        R.drawable.human4,
//        R.drawable.human5,
//        R.drawable.human6,
//        R.drawable.human7,
//        R.drawable.human8,
//        R.drawable.human9,
//        R.drawable.human10,
//        R.drawable.human11,
//        R.drawable.human12,
//        R.drawable.human13,
//        R.drawable.human14,
//        R.drawable.human15,
//        R.drawable.human16,
//        R.drawable.human17,
//        R.drawable.human18,
//        R.drawable.human19,
//        R.drawable.human20,
//        R.drawable.human21,
//        R.drawable.human22,
//        R.drawable.human23,
//        R.drawable.human24,
//        R.drawable.human25,
//        R.drawable.human26,
//        R.drawable.human27,
//        R.drawable.human28,
//        R.drawable.human29,
//        R.drawable.human30,
//        R.drawable.human31,
//        R.drawable.human32,
//        R.drawable.human33,
//        R.drawable.human34,
//        R.drawable.human35,
//        R.drawable.human36,
//        R.drawable.human37,
//        R.drawable.human38,
//        R.drawable.human39,
//        R.drawable.human40,
//        R.drawable.human41,
//        R.drawable.human42,
//        R.drawable.human43,
//        R.drawable.human44,
//        R.drawable.human45,
//        R.drawable.human46,
//        R.drawable.human47,
//        R.drawable.human48,
//        R.drawable.human49,
//        R.drawable.human50,
//    )
    val humanIcons = listOf(
        "human1",
        "human2",
        "human3",
        "human4",
        "human5",
        "human6",
        "human7",
        "human8",
        "human9",
        "human10",
        "human11",
        "human12",
        "human13",
        "human14",
        "human15",
        "human16",
        "human17",
        "human18",
        "human19",
        "human20",
        "human21",
        "human22",
        "human23",
        "human24",
        "human25",
        "human26",
        "human27",
        "human28",
        "human29",
        "human30",
        "human31",
        "human32",
        "human33",
        "human34",
        "human35",
        "human36",
        "human37",
        "human38",
        "human39",
        "human40",
        "human41",
        "human42",
        "human43",
        "human44",
        "human45",
        "human46",
        "human47",
        "human48",
        "human49",
        "human50",
    )
}