POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "email": "adron0914@gmail.com",
    "password": "123",
    "username": "adron",
    "nativeLanguage": "vie"
}

###

POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "usernameOrEmail": "adron2",
    "password": "123123"
}

###


GET http://localhost:4000/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNTk0ZWQxMDQtMWUzMi00YTM4LTllNDgtZDMxNzYwMjdkNTY1Iiwib2F1dGhJZCI6bnVsbCwidXNlcm5hbWUiOiJhZHJvbjIiLCJwYXNzd29yZCI6IiQyYiQxMCR6WWV1Y1dJeVNtN3Q3b3VlN1BtRFBleHdoM0JGZFJjZEtGazdWLlRRblNoU3RsTmkuUFEyMiIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImF2YXRhciI6bnVsbCwiZGFpbHlXb3JkQ291bnQiOjMsIm5vdGlmaWNhdGlvbkVuYWJsZWQiOnRydWUsIm5hdGl2ZUxhbmd1YWdlSWQiOiJ2aWUiLCJjcmVhdGVkQXQiOiIyMDIxLTA2LTI1VDIzOjI3OjEzLjA1NVoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA2LTI1VDIzOjI3OjEzLjA1NVoifSwiaWF0IjoxNjI1MTcxMDg1LCJleHAiOjE2MjU3NzU4ODV9.NdBGCKptSqvfC8RSgI3B4ITwXDHhX3iKt336CfEyCQc


###
GET http://localhost:4000/auth/verify/code
Content-Type: application/json

{
    "email": "adron0914@gmail.com"
}

###
POST http://localhost:4000/auth/verify/code
Content-Type: application/json

{
    "email": "adron0914@gmail.com",
    "code": "605191"
}

###

POST http://localhost:4000/auth/token
Content-Type: application/json

{
    "token": ".eyJ1c2VyIjp7ImlkIjoiNDJmMjBjYWQtNDkyNS00MjY4LWJhMDctM2VjNTEzZTExNWFjIiwib2F1dGhJZCI6bnVsbCwidXNlcm5hbWUiOiJhZHJvbiIsInBhc3N3b3JkIjoiJDJiJDEwJERTRTg5V1c5cFZVamUvb3U1VWR2Ny5PdTdtd1RrQXhBY3p2MS9ERlFJZkZ0QVdpM1VmekRLIiwiZW1haWwiOiJhZHJvbjA5MTRAZ21haWwuY29tIiwiYXZhdGFyIjpudWxsLCJkYWlseVdvcmRDb3VudCI6Mywibm90aWZpY2F0aW9uRW5hYmxlZCI6dHJ1ZSwibmF0aXZlTGFuZ3VhZ2VJZCI6InZpZSIsImNyZWF0ZWRBdCI6IjIwMjEtMDUtMTdUMDI6NDQ6MTYuMTI1WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDUtMTdUMDI6NDQ6MTYuMTI1WiJ9LCJpYXQiOjE2MjEyMjgwMTh9.cNFmV5R4v8NpGd_-yjkN7TgH8odo6zaWoO2nZ848MEk"
}


###

GET http://localhost:4000/word/daily?language=en_US



###
GET http://localhost:4000/word/definition?word=imperative&language=en_US



###
GET http://localhost:4000/word/autocomplete?text=hello&language=en_US



###
POST http://localhost:4000/word/save
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNzhjMGI4NTktYTA2Ni00ZGExLWEyNmYtYTFiZDdlMDFmYWU0Iiwib2F1dGhJZCI6bnVsbCwidXNlcm5hbWUiOiJhZHJvbiIsInBhc3N3b3JkIjoiJDJiJDEwJFZpNERTN1pSLnVJSGJ2UUxUaHJJUXVkT1dWR3BBVXFoV2g2bXlUUWN3cHJ0MEUuaXpkcUZtIiwiZW1haWwiOiJhZHJvbjA5MTRAZ21haWwuY29tIiwiYXZhdGFyIjpudWxsLCJkYWlseVdvcmRDb3VudCI6Mywibm90aWZpY2F0aW9uRW5hYmxlZCI6dHJ1ZSwibmF0aXZlTGFuZ3VhZ2VJZCI6InZpZSIsImNyZWF0ZWRBdCI6IjIwMjEtMDUtMjJUMjA6MDQ6MjcuMDg1WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDUtMjJUMjA6MDQ6MjcuMDg1WiJ9LCJpYXQiOjE2MjE3MTM4NzMsImV4cCI6MTYyMjMxODY3M30.HFDOu8xJCcgy-8blhsfOba7oQB-CCtbVeFihvNI7fqk
Content-Type: application/json

{
    "language": "en_US",
    "word": "test"
}


### 
GET http://localhost:4000/word/save
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNzhjMGI4NTktYTA2Ni00ZGExLWEyNmYtYTFiZDdlMDFmYWU0Iiwib2F1dGhJZCI6bnVsbCwidXNlcm5hbWUiOiJhZHJvbiIsInBhc3N3b3JkIjoiJDJiJDEwJFZpNERTN1pSLnVJSGJ2UUxUaHJJUXVkT1dWR3BBVXFoV2g2bXlUUWN3cHJ0MEUuaXpkcUZtIiwiZW1haWwiOiJhZHJvbjA5MTRAZ21haWwuY29tIiwiYXZhdGFyIjpudWxsLCJkYWlseVdvcmRDb3VudCI6Mywibm90aWZpY2F0aW9uRW5hYmxlZCI6dHJ1ZSwibmF0aXZlTGFuZ3VhZ2VJZCI6InZpZSIsImNyZWF0ZWRBdCI6IjIwMjEtMDUtMjJUMjA6MDQ6MjcuMDg1WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDUtMjJUMjA6MDQ6MjcuMDg1WiJ9LCJpYXQiOjE2MjE3MTM4NzMsImV4cCI6MTYyMjMxODY3M30.HFDOu8xJCcgy-8blhsfOba7oQB-CCtbVeFihvNI7fqk


###

PATCH http://localhost:4000/word/rearrange
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNzhjMGI4NTktYTA2Ni00ZGExLWEyNmYtYTFiZDdlMDFmYWU0Iiwib2F1dGhJZCI6bnVsbCwidXNlcm5hbWUiOiJhZHJvbiIsInBhc3N3b3JkIjoiJDJiJDEwJFZpNERTN1pSLnVJSGJ2UUxUaHJJUXVkT1dWR3BBVXFoV2g2bXlUUWN3cHJ0MEUuaXpkcUZtIiwiZW1haWwiOiJhZHJvbjA5MTRAZ21haWwuY29tIiwiYXZhdGFyIjpudWxsLCJkYWlseVdvcmRDb3VudCI6Mywibm90aWZpY2F0aW9uRW5hYmxlZCI6dHJ1ZSwibmF0aXZlTGFuZ3VhZ2VJZCI6InZpZSIsImNyZWF0ZWRBdCI6IjIwMjEtMDUtMjJUMjA6MDQ6MjcuMDg1WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDUtMjJUMjA6MDQ6MjcuMDg1WiJ9LCJpYXQiOjE2MjE3MTM4NzMsImV4cCI6MTYyMjMxODY3M30.HFDOu8xJCcgy-8blhsfOba7oQB-CCtbVeFihvNI7fqk
Content-Type: application/json

{
    "wordIds": [
        "9285580b-c212-4d49-9f22-f621091d0fef",
        "f7eac6d0-19b7-4a86-8321-3d2a7ab54ec3",
        "f7eac6d0-19b7-4a86-8321-3d2a7ab54ec3"
    ]
}

###

PATCH http://localhost:4000/word/definition/rearrange
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNzhjMGI4NTktYTA2Ni00ZGExLWEyNmYtYTFiZDdlMDFmYWU0Iiwib2F1dGhJZCI6bnVsbCwidXNlcm5hbWUiOiJhZHJvbiIsInBhc3N3b3JkIjoiJDJiJDEwJFZpNERTN1pSLnVJSGJ2UUxUaHJJUXVkT1dWR3BBVXFoV2g2bXlUUWN3cHJ0MEUuaXpkcUZtIiwiZW1haWwiOiJhZHJvbjA5MTRAZ21haWwuY29tIiwiYXZhdGFyIjpudWxsLCJkYWlseVdvcmRDb3VudCI6Mywibm90aWZpY2F0aW9uRW5hYmxlZCI6dHJ1ZSwibmF0aXZlTGFuZ3VhZ2VJZCI6InZpZSIsImNyZWF0ZWRBdCI6IjIwMjEtMDUtMjJUMjA6MDQ6MjcuMDg1WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDUtMjJUMjA6MDQ6MjcuMDg1WiJ9LCJpYXQiOjE2MjE3MTM4NzMsImV4cCI6MTYyMjMxODY3M30.HFDOu8xJCcgy-8blhsfOba7oQB-CCtbVeFihvNI7fqk
Content-Type: application/json

{
    "definitionIds": [
        "ec263413-fd91-4bac-afac-fe5ddc0aded8",
        "92de77b8-df6c-402b-bc8b-579aba61eef9",
        "b0cbc08d-45e6-4c7c-b21e-c9feb0ec07bf"
    ]
}

###

POST http://localhost:4000/language/save
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNTk0ZWQxMDQtMWUzMi00YTM4LTllNDgtZDMxNzYwMjdkNTY1Iiwib2F1dGhJZCI6bnVsbCwidXNlcm5hbWUiOiJhZHJvbjIiLCJwYXNzd29yZCI6IiQyYiQxMCR6WWV1Y1dJeVNtN3Q3b3VlN1BtRFBleHdoM0JGZFJjZEtGazdWLlRRblNoU3RsTmkuUFEyMiIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImF2YXRhciI6bnVsbCwiZGFpbHlXb3JkQ291bnQiOjMsIm5vdGlmaWNhdGlvbkVuYWJsZWQiOnRydWUsIm5hdGl2ZUxhbmd1YWdlSWQiOiJ2aWUiLCJjcmVhdGVkQXQiOiIyMDIxLTA2LTI1VDIzOjI3OjEzLjA1NVoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA2LTI1VDIzOjI3OjEzLjA1NVoifSwiaWF0IjoxNjI1MTcxMDg1LCJleHAiOjE2MjU3NzU4ODV9.NdBGCKptSqvfC8RSgI3B4ITwXDHhX3iKt336CfEyCQc
Content-Type: application/json

{
    "languages": ["en_US"]
}